### PR TITLE
Send key stroke to the game on hotkey pressed

### PR DESCRIPTION
**Pull request by theoliberman**
I thought that it might be good to be able to interact with markers (nodes, lore, etc...) and still be able to interact with the game.  It would then be able to harvest a node and update its timer on the website with a single key stroke. I did not tested this since I don't have an Overwolf developer account but if I understood the documentation correctly, it should work.

### CODE REVIEW

**Comment by lmachens** [comment]
This is an interesting use case, thank you for your pull request.
Actually, I didn't know that the hotkey is not forwarded to the game right now.
I will try this out later or tomorrow :). 

Which hotkey would you use for harvest/timer?

**Comment by theoliberman** [comment]
I personally use "E" as the default harvest key.
There is maybe something to do with the notifications on "no marker" situations when the key is used for something else (Talking to an NPC for example or quest related interactions).

**Comment by lmachens** [comment]
Right, in addition, if you are writing in chat, it could be confusing.
If this is implemented and `E` is used, I agree that we need to rethink "no marker".

Is there any issue if the default hotkey (F11?) is forwarded to New World?
If not, your change shouldn't break anything.

**Comment by lmachens** [comment]
The `passthrough` option solves your issue:
https://overwolf.github.io/api/manifest#hotkeys-object

I updated this pull request and removed the "not found" warnings, if there is not action or marker found.

In addition, I changed the default hotkey to `E`.
This might be confusing for some users, but they will definitely see this feature in action if they didn't no it.

**Pull request merged**
